"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

fib = [1,2]
fib_sum = 2
i = 2


while True:
  num = fib[i-1] + fib[i-2]
  if num < 4000000:
    fib.append(num)
    if num%2 == 0:
      fib_sum += num
  else:
    break
  i += 1

print("Total sum is: %d" % fib_sum)